### ISSUE TITLE
Mechanism for PPOJOs with no default ctor

### ISSUE THREAD

**Issue by dima767** [xrrocha/yamltag#1]
It would be extremely useful to (somehow) implement a custom tag mapping mechanism for classes with no default ctors (e.g. immutable classes). So for example:

``` java
package my.package;
public class Car {
   private String make;

   Car(String make) {
      this.make;
   }
   ...
}
```

could be somehow represented and instantiated by SnakeYaml like so:

``` yaml
!car(Toyota)
```

or

``` yaml
!car {make: Toyota}
```

This seems to work (combination of yamltag `car` and SnakeYAML's compact object notation), but it's kind of "ugly":

``` yaml
!car my.package.Car(Toyota)
```

**Comment by xrrocha** [comment]
Hi Dmitriy, thanks for your request!

It is already possible to invoke a non-empty constructor with a tag (thanks to SnakeYaml's superb tag and constructor support).

Thus, given the following Java class:

``` java
package net.xrrocha.yamltag.example;
public class Term {
    private String englishWord;
    Map<Language, String> translations;
    public Term(String englishWord, Map<Language, String> translations) {
        this.englishWord = englishWord;
        this.translations = translations;
    }
    // accessors elided...
}
```

and the following `yamltag.yaml`:

``` yaml
net.xrrocha.yamltag.example.Term:
    tagName: term
```

then the following Yaml string will work as advertised:

``` yaml
!term ['term', {
  russian: срок,
  spanish: término
}]
```

The above can be shortened to:

``` yaml
!term ['term', { russian: срок, spanish: término }]
```

I have added a unit test illustrating this.

**Comment by dima767** [comment]
Thank you.

—
